name: INFRA - plan shared services - NONPROD

run-name: Validate Infra shared services
on:
  pull_request:
    paths:
    - 'infra/_sharedservices/*.tf'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-plan
  cancel-in-progress: false

jobs:
  call_terraform_router:
    name: Terraform Router
    uses: littlejo/github-action-test/.github/workflows/action.yaml@toto-test
    with:
      scope: "sharedservices"
      environment: "na"
      action: "plan"
    secrets: inherit
