name: INFRA - plan - NONPROD

run-name: Validate Infra 
on:
  pull_request:
    paths:
    - 'infra/*/*/*.tf'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-plan
  cancel-in-progress: false

jobs:

  locate_tf_file:
    name: Find where do you plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: check_app_env
        name: Match env with app
        run: |
          DEFAULT_BRANCH=$(LANG=C git remote show origin | grep 'HEAD branch:' | awk '{print $NF}')
          BASE=$(git merge-base origin/$DEFAULT_BRANCH HEAD)
          dirs=$(dirname $(git diff --name-only $BASE HEAD | grep 'infra' | grep '\.tf') | sort | uniq)
          matrix=$(echo "$dirs" | awk -F'/' '{printf("{\"environment\": \"%s\", \"scope\": \"%s\"}\n", $3, $2)}' | jq -c -s '.')
          echo "myoutput=$matrix" >> $GITHUB_OUTPUT
    outputs:
      mymatrix: ${{ steps.check_app_env.outputs.myoutput }}

  call_terraform_router:
    name: Terraform Router
    runs-on: ubuntu-latest
    needs: locate_tf_file
    strategy:
      matrix:
        infra: ${{ fromJson(needs.locate_tf_file.outputs.mymatrix) }}
    steps:
      - uses: actions/checkout@v4

      - id: test_file
        name: Test file
        run: ls infra/${{ matrix.infra.scope }}/${{ matrix.infra.env }}
